[versions]
agp = "8.3.0"
jalalicalendar = "1.3.3"
jalaliDatepickerCompose = "1.2.0"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.12.01"
ksp = "2.0.0-1.0.24"
hiltVersion = "2.51.1"
appcompat = "1.7.0"
material = "1.12.0"
lottieCompose = "4.0.0"
progressIndicator = "0.2.0"
composeLivedata = "1.7.6"
composeNavigation = "2.8.5"
roomAndroid = "2.6.1"
shimmerEffect = "1.3.0"
hiltNavigaion = "1.2.0"
junitJupiter = "5.8.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
jalali-datepicker-compose = { module = "com.github.hamooo90:jalali-datepicker-compose", version.ref = "jalaliDatepickerCompose" }
jalalicalendar = { module = "ir.huri:JalaliCalendar", version.ref = "jalalicalendar" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
hilt-android = { group = "com.google.dagger", name = "hilt-android" , version.ref = "hiltVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler" , version.ref = "hiltVersion" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose" , version.ref = "hiltNavigaion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
lottieCompose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieCompose" }
progressIndicator = { group = "com.ehsanmsz", name = "msz-progress-indicator", version.ref = "progressIndicator" }
composeLivedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "composeLivedata" }
composeNavigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
room-android = { group =  "androidx.room", name = "room-runtime" , version.ref =  "roomAndroid" }
room-compiler = { group = "androidx.room", name = "room-compiler" , version.ref = "roomAndroid" }
shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer" , version.ref = "shimmerEffect" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }



[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = {id = "com.google.devtools.ksp" ,version.ref = "ksp"}
hilt = {id = "com.google.dagger.hilt.android" ,version.ref = "hiltVersion" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }